version: '3.3'
services:
  tinder-client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_URL: localhost
    container_name: tinder-client
    ports:
      - "80:80"
    networks:
      - tinder-network
    depends_on:
      - tinder-api
      - tinder-db

  tinder-api:
    build:
      context: ./Backend/
      dockerfile: Dockerfile
    container_name: tinder-api
    environment:
      - MONGOURL=tinder-db
    ports:
      - "8000:8000"
    networks:
      - tinder-network
    volumes:
      - tinderdata:/usr/src/app
    depends_on:
      - tinder-db

  tinder-db:
    image: mongo:3.6.19-xenial
    restart: unless-stopped
    container_name: tinder-db
    networks: 
      - tinder-network
    volumes:
      - tinderdb:/data/db 

networks:
    tinder-network:
      driver: bridge
volumes:
    tinderdb: {}
    tinderdata: {}