apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinder-api
  labels:
    app: tinder-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tinder-api
  template:
    metadata:
      labels:
        app: tinder-api
    spec:
      initContainers:
        - name: init-db
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of MongoDB Server deployment"; while ! nc -z mongodb-service 27017; do sleep 1; printf "-"; done; echo -e "  >> MongoDB Server has started";']
      containers:
        - name: tinder-api
          image: dineshtamang14/tinder-api
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_HOST
              value: "mongodb-service"
            - name: MONGO_PORT
              value: "27017"

      #     volumeMounts:
      #       - name: tinder-api-storage
      #         mountPath: /usr/src/app

      # volumes:
      #   - name: tinder-api-storage
      #     persistentVolumeClaim:
      #       claimName: ebs-tinder-api-pvc
