apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-tinder-api-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 2Gi
      